services:
  - type: web
    name: wish-map-web
    runtime: static
    branch: main
    buildCommand: npm ci && npx expo export --platform web --clear
    staticPublishPath: ./dist
    envVars:
      - key: EXPO_NO_DOTENV
        value: "1"
      - key: EXPO_PUBLIC_API_URL
        value: https://api.wishmap.kr
      - key: EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID
        value: 386596705781-mp70rdrp1ulj6dovlqs0doig1t56592r.apps.googleusercontent.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
